version: '3'
volumes:
  postgrescontinentdata:
services:
  postgrescontinentdb:
    build: ./postgres
    network_mode: bridge
    # Give the container the name.
    container_name: postgrescontinentdb
    # Set a volume some that database is not lost after shutting down the container.
    volumes:
      - postgrescontinentdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nation
    restart: unless-stopped
    # Service health check
    healthcheck:
      test: pg_isready -d nation -h postgrescontinentdb -p 5432 -U root
      interval: 1m
      timeout: 10s
      retries: 2

  continentinfoapp:
    build: ./continent-info-service
    network_mode: bridge
    container_name: continentinfoapp
    expose:
      - 8082
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgrescontinentdb:5432/nation
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - postgrescontinentdb
    links:
      - postgrescontinentdb